// Unicode
#define UNI_A    UC(0x61) // Latin small letter "a"
#define UNI_B    UC(0x62) // Latin small letter "b"
#define UNI_C    UC(0x63) // Latin small letter "c"
#define UNI_D    UC(0x64) // Latin small letter "d"
#define UNI_E    UC(0x65) // Latin small letter "e"
#define UNI_F    UC(0x66) // Latin small letter "f"
#define UNI_G    UC(0x67) // Latin small letter "g"
#define UNI_H    UC(0x68) // Latin small letter "h"
#define UNI_I    UC(0x69) // Latin small letter "i"
#define UNI_J    UC(0x6A) // Latin small letter "j"
#define UNI_K    UC(0x6B) // Latin small letter "k"
#define UNI_L    UC(0x6C) // Latin small letter "l"
#define UNI_M    UC(0x6D) // Latin small letter "m"
#define UNI_N    UC(0x6E) // Latin small letter "n"
#define UNI_O    UC(0x6F) // Latin small letter "o"
#define UNI_P    UC(0x70) // Latin small letter "p"
#define UNI_Q    UC(0x71) // Latin small letter "q"
#define UNI_R    UC(0x72) // Latin small letter "r"
#define UNI_S    UC(0x73) // Latin small letter "s"
#define UNI_T    UC(0x74) // Latin small letter "t"
#define UNI_U    UC(0x75) // Latin small letter "u"
#define UNI_V    UC(0x76) // Latin small letter "v"
#define UNI_W    UC(0x77) // Latin small letter "w"
#define UNI_X    UC(0x78) // Latin small letter "x"
#define UNI_Y    UC(0x79) // Latin small letter "y"
#define UNI_Z    UC(0x7A) // Latin small letter "z"


#define U_RSQM   UC(0x2019) // Right Single Quotation Mark
